name: GitHub Actions For S3 AWS Deployment
run-name: ${{ github.actor }} deploy en S3 AWS 🚀
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies 🔰
        run: npm i
      - name: Run Build 🛠
        run: npm run build
        env:
          CI: false
          REACT_APP_UNSPLASH_API_KEY: ${{ secrets.REACT_APP_UNSPLASH_API_KEY }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          REACT_APP_UNSPLASH_API_KEY: ${{ secrets.REACT_APP_UNSPLASH_API_KEY }}
          file_name: .env.local
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-3'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository


        